server:
  port: 9092


spring:
  datasource:
    username: root
    url: jdbc:mysql://www.cjlly.com:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  application:
    name: nacos-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


management:
  endpoints:
    web:
      exposure:
        include: '*'