server:
  port: 8082

spring:
  datasource:
    username: root
    url: jdbc:mysql://www.cjlly.com:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#消费者将要去访问的微服务名称（成功注册进naocs的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-service